version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
  - CI
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/GraphQl.NetStandard.Client.sln --verbosity m
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./tests/GraphQL.NetStandard.Client.UnitTests/GraphQL.NetStandard.Client.UnitTests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd tests/GraphQL.NetStandard.Client.UnitTests/bin/Debug/netcoreapp2.0/
  - cmd: dotnet-vstest GraphQL.NetStandard.Client.UnitTests.dll /logger:Appveyor
on_finish :
  # any cleanup in here
deploy:
  provider: NuGet
  api_key:
    secure: NAVDoWNLP4nv5EVqU4/mCtr1Gy1hX8z85W1UVH9EIG9Nmww+USgF6jTm0MiAyRgf
  skip_symbols: false
  artifact: /.*\.nupkg/
